# Semana 1
Semana 1 do Desafio Quadro do Trello: https://trello.com/c/QQnFo42q/8-corrigir-as-inconsist%C3%AAncias-nos-dados

## Obter e Formatar
 Card: "Churn de Clientes"

In [ ]:
import pandas as pd
import json
from urllib.request import urlopen

pd.set_option("display.max_rows", 999)

Visualização do Json: http://jsonviewer.stack.hu/#https://raw.githubusercontent.com/sthemonica/alura-voz/main/Dados/Telco-Customer-Churn.json

In [ ]:
url = 'https://raw.githubusercontent.com/sthemonica/alura-voz/main/Dados/Telco-Customer-Churn.json'
response = urlopen(url)
strfile = response.read().decode('utf-8', 'replace')
jsonfile = json.loads(strfile)
base = pd.read_json(url)
jsonfile

## Familiarizar com os dados
Card: "Entender quais informações o conjunto de dados possui"

In [ ]:
main_data = pd.json_normalize(data=jsonfile)
customer_data = pd.json_normalize(data=base.customer)
phone_data = pd.json_normalize(data=base.phone)
internet_data = pd.json_normalize(data=base.internet)
contract_data = pd.json_normalize(data=base.account)
main_data

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

## Tipos de Dados
Card: "Analisar quais os tipos de dados"

In [ ]:
for coluna in main_data.columns:
  print(f'Column: {coluna}, Unique Values:{main_data[coluna].unique()}')

Column: customerID, Unique Values:['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Column: Churn, Unique Values:['No' 'Yes' '']
Column: customer.gender, Unique Values:['Female' 'Male']
Column: customer.SeniorCitizen, Unique Values:[0 1]
Column: customer.Partner, Unique Values:['Yes' 'No']
Column: customer.Dependents, Unique Values:['Yes' 'No']
Column: customer.tenure, Unique Values:[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
Column: phone.PhoneService, Unique Values:['Yes' 'No']
Column: phone.MultipleLines, Unique Values:['No' 'Yes' 'No phone service']
Column: internet.InternetService, Unique Values:['DSL' 'Fiber optic' 'No']
Column: internet.OnlineSecurity, Unique Values:['No' 'Yes' 'No internet service']
Column: internet.OnlineBackup, Unique Values:['Yes' 'No' 'No internet service']
Column: internet.DeviceProtection, Unique Values:['No' 'Yes' 'No internet service']
Column: internet.TechSupport, Unique Values:['Yes' 'No' 'No internet service']
Column: internet.StreamingTV, Unique Values:['Yes' 'No' 'No internet service']
Column: internet.StreamingMovies, Unique Values:['No' 'Yes' 'No internet service']
Column: account.Contract, Unique Values:['One year' 'Month-to-month' 'Two year']
Column: account.PaperlessBilling, Unique Values:['Yes' 'No']
Column: account.PaymentMethod, Unique Values:['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
Column: account.Charges.Monthly, Unique Values:[65.6  59.9  73.9  ... 91.75 68.8  67.85]
Column: account.Charges.Total, Unique Values:['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

In [ ]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

## Incossistências
Card: Verificar quais são as inconsistências nos dados

In [ ]:
main_data['Churn'].unique() #Has balnk

array(['No', 'Yes', ''], dtype=object)

In [ ]:
main_data['customer.SeniorCitizen'].unique() #Use 1/0 insted of Yes/No
main_data['phone.MultipleLines'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.OnlineSecurity'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.OnlineBackup'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.DeviceProtection'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.TechSupport'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.StreamingTV'].unique() #Has 'No X Service' insted of 'no'
main_data['internet.StreamingMovies'].unique() #Has 'No X Service' insted of 'no'

array([0, 1])

In [ ]:
main_data['account.Charges.Total'].unique() #Formated as String not Decimal

array(['593.3', '542.4', '280.85', ..., '742.9', '4627.65', '3707.6'],
      dtype=object)

## Correções
Card: Corrigir as inconsistências nos dados

In [ ]:
#Has balnk
main_data.Churn = main_data['Churn'].replace([''], 'Unkonow') 

#Use 1/0 insted of Yes/No and 'No X Service' insted of 'no'
columns_to_ajust = ['customer.SeniorCitizen', 'phone.MultipleLines', 'internet.OnlineSecurity', 'internet.OnlineBackup', 'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV', 'internet.StreamingMovies']
for column in columns_to_ajust:
  main_data[column] = main_data[column].replace(['No internet service', 'No phone service', 0], 'No').replace([1], 'Yes')

#Formated as String not Number
main_data['account.Charges.Total'] = main_data['account.Charges.Total'].replace([' '], '0')
main_data['account.Charges.Total'] = pd.to_numeric(main_data['account.Charges.Total'])

main_data

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,No,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.90
7263,9992-RRAMN,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70
7264,9992-UJOEL,No,Male,No,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,No,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,No,Yes,Yes,63,No,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60

## Extra 2: Adicionar Contas Diárias
Card: Criar coluna de contas diárias | Ele será feito antes do Extra 1.

In [42]:
main_data["account.Charges.Day"] = (
    main_data["account.Charges.Monthly"] / 30
)
main_data

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,account.Charges.Day
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,No,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,No,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,No,Yes,Yes,63,No,No,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667

## Extra 1 - Tradução
Card: Traduzir as colunas | Feito depois do Extra 2, para que a nova coluna possa ser traduziada

In [43]:
columns_dictionary = {
  'customerID': 'ID do cliente',
  'Churn': 'Deixou a empresa',
  'customer.gender': 'Gênero',
  'customer.SeniorCitizen': 'Mais de 65 anos',
  'customer.Partner': 'Com parceiro(a)',
  'customer.Dependents': 'Com dependentes',
  'customer.tenure': 'Meses de Permanencia',
  'phone.PhoneService': 'Assina Telefone',
  'phone.MultipleLines': 'Assina Várias linhas',
  'internet.InternetService': 'Assina Internet',
  'internet.OnlineSecurity': 'Assina Segurança online',
  'internet.OnlineBackup': 'Assina Backup online',
  'internet.DeviceProtection': 'Assina Proteção de dispositivos',
  'internet.TechSupport': 'Assina Suporte',
  'internet.StreamingTV': 'Assina Streaming TV',
  'internet.StreamingMovies': 'Assina Streaming Filmes',
  'account.Contract': 'Contrato',
  'account.PaperlessBilling': 'Conta online',
  'account.PaymentMethod': 'Forma de pagamento',
  'account.Charges.Monthly': 'Gasto mensal',
  'account.Charges.Total': 'Gasto total',
  'account.Charges.Day': 'Gasto Diário',
 }
dados_principais = main_data.rename(columns_dictionary, axis='columns')
dados_principais

,ID do cliente,Deixou a empresa,Gênero,Mais de 65 anos,Com parceiro(a),Com dependentes,Meses de Permanencia,Assina Telefone,Assina Várias linhas,Assina Internet,...,Assina Proteção de dispositivos,Assina Suporte,Assina Streaming TV,Assina Streaming Filmes,Contrato,Conta online,Forma de pagamento,Gasto mensal,Gasto total,Gasto Diário
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.30,2.186667
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.40,1.996667
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85,2.463333
3,0011-IGKFF,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.40,2.796667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,No,No,No,13,Yes,No,DSL,...,No,Yes,No,No,One year,No,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,No,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,No,Male,No,Yes,Yes,67,Yes,No,DSL,...,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,No,Male,No,Yes,Yes,63,No,No,DSL,...,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.60,1.966667